# Generated by Django 5.0.1 on 2024-01-31 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_rename_pages_page_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
    ]
